from typing import Protocol
from uuid import UUID
from modules.restaurants.model import Restaurant


class IRestaurantRepository(Protocol):
    async def get(self, id: UUID) -> Restaurant | None: ...
    async def get_by_slug(self, slug: str) -> Restaurant | None: ...
    async def get_by_owner(self, owner_id: UUID) -> list[Restaurant]: ...
    async def list_active(self, limit: int, offset: int) -> list[Restaurant]: ...
    async def create(self, obj_in: Restaurant) -> Restaurant: ...
    async def update(self, instance: Restaurant, **kwargs) -> Restaurant: ...
    async def delete(self, obj: Restaurant) -> None: ...